/**
 * @module agent-protocol
 *
 * Core agent protocol types governing how the AI agent plans, previews,
 * approves, and executes multi-step editing workflows. The plan/step
 * model is the backbone of the agentic editing experience, supporting
 * manual approval gates, auto-approve policies, and dry-run mode.
 */

// ─── Status Types ─────────────────────────────────────────────────────────────

/**
 * Lifecycle status of an agent plan.
 * - `planning`   — the agent is still generating the plan
 * - `preview`    — plan is ready for user review
 * - `approved`   — user has approved execution
 * - `executing`  — steps are being executed
 * - `completed`  — all steps finished successfully
 * - `failed`     — one or more steps failed without recovery
 * - `cancelled`  — user cancelled the plan
 */
export type PlanStatus =
  | 'planning'
  | 'preview'
  | 'approved'
  | 'executing'
  | 'completed'
  | 'failed'
  | 'cancelled';

/**
 * Lifecycle status of an individual step within a plan.
 * - `pending`      — not yet started
 * - `approved`     — explicitly approved by the user
 * - `executing`    — currently running
 * - `completed`    — finished successfully
 * - `failed`       — execution failed
 * - `cancelled`    — skipped by user or plan cancellation
 * - `compensated`  — a rollback action reversed this step's effect
 */
export type StepStatus =
  | 'pending'
  | 'approved'
  | 'executing'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'compensated';

/**
 * Execution mode for plan steps.
 * - `sequential`  — steps run one after another
 * - `parallel`    — independent steps may run concurrently
 * - `conditional` — steps are gated on runtime predicates
 */
export type ExecutionMode = 'sequential' | 'parallel' | 'conditional';

// ─── Approval Policy ──────────────────────────────────────────────────────────

/**
 * Configures how plan steps are approved before execution.
 *
 * In `manual` mode every step requires explicit user approval.
 * In `auto-approve` mode, steps whose tool names appear in
 * `allowedAutoTools` execute without confirmation (up to `maxAutoTokens`).
 * `dry-run` mode simulates execution without side-effects.
 */
export interface ApprovalPolicy {
  /** Approval mode governing step execution. */
  readonly mode: 'manual' | 'auto-approve' | 'dry-run';
  /** Tool names that may execute without explicit user approval. */
  readonly allowedAutoTools: readonly string[];
  /** Tool names that always require explicit user approval, even in auto mode. */
  readonly requireApprovalFor: readonly string[];
  /** Maximum cumulative token spend before auto-approve is paused. */
  readonly maxAutoTokens: number;
}

// ─── Agent Step ───────────────────────────────────────────────────────────────

/**
 * A single discrete operation within an agent plan.
 *
 * Each step maps to exactly one tool invocation. Steps carry their own
 * status, timing, and optional compensation action for rollback.
 */
export interface AgentStep {
  /** Unique step identifier. */
  readonly id: string;
  /** Parent plan identifier. */
  readonly planId: string;
  /** Zero-based execution order within the plan. */
  readonly index: number;
  /** Human-readable description of what this step does. */
  readonly description: string;
  /** Canonical name of the tool to invoke. */
  readonly toolName: string;
  /** Arguments to pass to the tool. */
  readonly toolArgs: Readonly<Record<string, unknown>>;
  /** Current lifecycle status. */
  readonly status: StepStatus;
  /** Serialised tool result on success, or `null`. */
  readonly result: unknown | null;
  /** Error detail on failure, or `null`. */
  readonly error: unknown | null;
  /** Compensation action descriptor for rollback, or `null`. */
  readonly compensation: string | null;
  /** ISO 8601 timestamp when execution started, or `null`. */
  readonly startedAt: string | null;
  /** ISO 8601 timestamp when execution completed, or `null`. */
  readonly completedAt: string | null;
  /** Wall-clock duration in milliseconds, or `null`. */
  readonly durationMs: number | null;
}

// ─── Agent Plan ───────────────────────────────────────────────────────────────

/**
 * A multi-step execution plan generated by the AI agent.
 *
 * Plans are the top-level unit of agentic work. They capture the user's
 * intent, the ordered steps the agent proposes, cost estimates, and the
 * approval policy that governs execution.
 */
export interface AgentPlan {
  /** Unique plan identifier. */
  readonly id: string;
  /** Natural-language summary of the user's editing intent. */
  readonly intent: string;
  /** Ordered list of steps the agent proposes to execute. */
  readonly steps: readonly AgentStep[];
  /** Current lifecycle status of the plan. */
  readonly status: PlanStatus;
  /** Estimated total token cost before execution. */
  readonly tokensEstimated: number;
  /** Actual tokens consumed so far. */
  readonly tokensUsed: number;
  /** ISO 8601 creation timestamp. */
  readonly createdAt: string;
  /** ISO 8601 last-update timestamp. */
  readonly updatedAt: string;
  /** Approval policy governing how steps are authorised. */
  readonly approvalPolicy: ApprovalPolicy;
}

// ─── Agent Context ────────────────────────────────────────────────────────────

/**
 * Ambient context passed to the agent at plan-generation time.
 *
 * Captures the current editing state so the agent can make informed
 * decisions about which tools to invoke and with what arguments.
 */
export interface AgentContext {
  /** Active project identifier. */
  readonly projectId: string;
  /** Active sequence identifier. */
  readonly sequenceId: string;
  /** Currently open bin IDs. */
  readonly binIds: readonly string[];
  /** Currently selected clip IDs in the timeline. */
  readonly selectedClipIds: readonly string[];
  /** Current playhead position in seconds. */
  readonly playheadTime: number;
  /** Active search query, or `null`. */
  readonly searchQuery: string | null;
  /** IDs of search results currently visible, or `null`. */
  readonly searchResults: readonly string[] | null;
  /** Transcript segments surrounding the playhead, or `null`. */
  readonly transcriptContext: readonly string[] | null;
  /** Mesh peer node IDs contributing to the current session, or `null`. */
  readonly meshNodes: readonly string[] | null;
}
