// ═══════════════════════════════════════════════════════════════════════════
//  THE AVID — Creator Workflow Types (CC-01 through CC-09)
// ═══════════════════════════════════════════════════════════════════════════

// ─── Aspect Ratio ─────────────────────────────────────────────────────────

export interface AspectRatio {
  width: number;
  height: number;
  label: string; // e.g. '16:9', '9:16', '1:1'
}

export const ASPECT_RATIOS: Record<string, AspectRatio> = {
  '16:9': { width: 16, height: 9, label: '16:9' },
  '9:16': { width: 9, height: 16, label: '9:16' },
  '1:1': { width: 1, height: 1, label: '1:1' },
  '4:5': { width: 4, height: 5, label: '4:5' },
  '4:3': { width: 4, height: 3, label: '4:3' },
  '21:9': { width: 21, height: 9, label: '21:9' },
};

// ─── Auto-Reframe (CC-01) ────────────────────────────────────────────────

export type SubjectType = 'face' | 'salient_object' | 'action_center' | 'custom_region';

export interface DetectedSubject {
  type: SubjectType;
  confidence: number;
  boundingBox: { x: number; y: number; width: number; height: number };
  trackId?: string;
}

export interface AutoReframeConfig {
  sourceAspect: AspectRatio;
  targetAspect: AspectRatio;
  subjectLockStrength: number;  // 0-1, how tightly the crop follows the subject
  motionSmoothing: number;      // 0-1, smoothing factor for crop motion
  subjectPriority: SubjectType[];
  safeZoneMargin: number;       // 0-0.2, margin around detected subject
}

export interface ReframeKeyframe {
  time: number;
  cropRegion: { x: number; y: number; width: number; height: number };
  subjects: DetectedSubject[];
}

export interface ReframeResult {
  clipId: string;
  sourceAspect: AspectRatio;
  targetAspect: AspectRatio;
  keyframes: ReframeKeyframe[];
  subjectRetentionScore: number; // 0-1, percentage of frames with subject visible
  status: 'pending' | 'processing' | 'completed' | 'failed';
  error?: string;
}

// ─── Chapter Markers (CC-02) ─────────────────────────────────────────────

export interface ChapterMarker {
  time: number;           // seconds from start
  title: string;
  description?: string;
  thumbnailTime?: number; // optional override for chapter thumbnail
  isAutoGenerated: boolean;
  confidence?: number;    // 0-1 for AI-generated chapters
}

export interface YouTubeMetadata {
  title: string;
  description: string;
  tags: string[];
  category?: string;
  visibility: 'public' | 'unlisted' | 'private';
  chapters: ChapterMarker[];
  scheduledPublishTime?: string;
}

export type ChapterExportFormat = 'youtube' | 'srt_chapters' | 'json' | 'markdown';

// ─── Thumbnail Designer (CC-03) ──────────────────────────────────────────

export interface TextOverlay {
  id: string;
  text: string;
  position: { x: number; y: number };
  fontSize: number;
  fontFamily: string;
  fontWeight: number;
  color: string;
  strokeColor?: string;
  strokeWidth?: number;
  shadowColor?: string;
  shadowBlur?: number;
  rotation: number;
  opacity: number;
  maxWidth?: number;
}

export type ThumbnailBackground =
  | { type: 'frame'; frameTime: number }
  | { type: 'solid'; color: string }
  | { type: 'gradient'; colors: string[]; angle: number }
  | { type: 'blur'; frameTime: number; blurRadius: number }
  | { type: 'custom'; imageUrl: string };

export interface ColorBoostPreset {
  id: string;
  name: string;
  saturation: number;    // 0-2, 1 = normal
  contrast: number;      // 0-2, 1 = normal
  brightness: number;    // 0-2, 1 = normal
  warmth: number;        // -1 to 1, 0 = neutral
  vibrance: number;      // 0-2, 1 = normal
}

export interface ThumbnailExportSize {
  width: number;
  height: number;
  label: string;
}

export const THUMBNAIL_EXPORT_SIZES: ThumbnailExportSize[] = [
  { width: 1280, height: 720, label: 'YouTube (1280x720)' },
  { width: 1080, height: 1920, label: 'Story/Reel (1080x1920)' },
  { width: 1080, height: 1080, label: 'Square (1080x1080)' },
  { width: 1200, height: 628, label: 'Open Graph (1200x628)' },
];

export interface ThumbnailDesign {
  id: string;
  frameTime: number;
  textOverlays: TextOverlay[];
  background: ThumbnailBackground;
  colorBoost: ColorBoostPreset | null;
  exportSize: ThumbnailExportSize;
  faceCutout?: {
    enabled: boolean;
    scale: number;
    position: { x: number; y: number };
    borderColor?: string;
    borderWidth?: number;
  };
  createdAt: string;
  updatedAt: string;
}

export interface ThumbnailCandidate {
  frameTime: number;
  score: number;          // 0-1, AI quality/relevance score
  reason: string;         // why this frame was selected
  hasFaces: boolean;
  dominantColors: string[];
}

// ─── Stock Music (CC-04) ─────────────────────────────────────────────────

export type MusicMood =
  | 'happy' | 'sad' | 'energetic' | 'calm' | 'dramatic'
  | 'mysterious' | 'romantic' | 'dark' | 'uplifting' | 'ambient'
  | 'cinematic' | 'corporate' | 'playful' | 'tense' | 'epic';

export type MusicGenre =
  | 'pop' | 'rock' | 'electronic' | 'hip_hop' | 'classical'
  | 'jazz' | 'folk' | 'ambient' | 'cinematic' | 'lofi'
  | 'rnb' | 'country' | 'reggae' | 'metal' | 'indie';

export type StockMusicProvider = 'artlist' | 'epidemic_sound' | 'musicbed' | 'soundstripe';

export interface StockMusicSearchParams {
  query?: string;
  mood?: MusicMood[];
  genre?: MusicGenre[];
  tempo?: { min: number; max: number }; // BPM range
  energy?: 'low' | 'medium' | 'high';
  duration?: { min: number; max: number }; // seconds
  instrumental?: boolean;
  providers?: StockMusicProvider[];
  page?: number;
  pageSize?: number;
}

export interface StockMusicResult {
  id: string;
  title: string;
  artist: string;
  mood: MusicMood[];
  genre: MusicGenre[];
  tempo: number;            // BPM
  energy: 'low' | 'medium' | 'high';
  duration: number;         // seconds
  previewUrl: string;
  downloadUrl?: string;
  licenseUrl: string;
  provider: StockMusicProvider;
  waveformData?: number[];
  key?: string;             // musical key
  tags: string[];
}

export interface MusicLicense {
  id: string;
  trackId: string;
  provider: StockMusicProvider;
  type: 'standard' | 'premium' | 'enterprise';
  projectId: string;
  grantedAt: string;
  expiresAt?: string;
}

export interface BeatMarker {
  time: number;
  strength: number;  // 0-1, beat intensity
  type: 'downbeat' | 'beat' | 'offbeat';
}

// ─── Stock Video (CC-05) ─────────────────────────────────────────────────

export type StockVideoProvider = 'artgrid' | 'shutterstock' | 'getty';

export interface StockVideoSearchParams {
  query?: string;
  keywords?: string[];
  mood?: string;
  aspectRatio?: '16:9' | '9:16' | '1:1' | '4:3';
  resolution?: 'hd' | '4k' | '8k';
  duration?: { min: number; max: number };
  fps?: number;
  providers?: StockVideoProvider[];
  page?: number;
  pageSize?: number;
}

export interface StockVideoResult {
  id: string;
  title: string;
  description: string;
  keywords: string[];
  previewUrl: string;
  downloadUrl?: string;
  provider: StockVideoProvider;
  resolution: { width: number; height: number };
  duration: number;
  fps: number;
  codec?: string;
  thumbnailUrl: string;
  licenseUrl: string;
}

export interface BRollSuggestion {
  transcriptCueId: string;
  query: string;
  reason: string;
  suggestedResults: StockVideoResult[];
  confidence: number;
}

// ─── Beat Sync (CC-06) ───────────────────────────────────────────────────

export type BeatSyncMode = 'auto_cut' | 'markers' | 'speed_ramp';

export interface BeatSyncConfig {
  mode: BeatSyncMode;
  beatThreshold: number;       // 0-1, minimum beat strength to sync to
  sourceClipIds: string[];
  audioTrackId?: string;       // which audio track to detect beats from
  everyNBeats: number;         // for auto_cut: cut every N beats (1, 2, 4)
  speedRampIntensity?: number; // 0-1, how much speed variation in ramp mode
  quantize?: boolean;          // snap cuts to nearest beat
  transitionType?: 'cut' | 'crossfade' | 'whip';
  transitionDuration?: number; // seconds
}

export interface BeatSyncResult {
  id: string;
  config: BeatSyncConfig;
  detectedBPM: number;
  beats: BeatMarker[];
  cuts: Array<{ time: number; clipId: string }>;
  markers: Array<{ time: number; label: string }>;
  speedKeyframes?: Array<{ time: number; speed: number }>;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  error?: string;
}

// ─── Series Manager (CC-07) ──────────────────────────────────────────────

export type EpisodeStatus = 'idea' | 'scripted' | 'filming' | 'editing' | 'review' | 'published';

export interface BrandAsset {
  id: string;
  name: string;
  type: 'logo' | 'intro' | 'outro' | 'watermark' | 'lower_third' | 'font' | 'color_palette' | 'music_sting';
  url: string;
  thumbnailUrl?: string;
  metadata: Record<string, unknown>;
}

export interface EpisodeAnalytics {
  views: number;
  likes: number;
  comments: number;
  watchTimeMinutes: number;
  averageViewDuration: number; // seconds
  clickThroughRate: number;    // 0-1
  retentionCurve: number[];   // 0-1 values, sampled at regular intervals
  publishedAt: string;
  platform: string;
}

export interface SeriesEpisode {
  id: string;
  projectId: string;
  episodeNumber: number;
  title: string;
  description: string;
  status: EpisodeStatus;
  thumbnailUrl?: string;
  duration?: number;
  publishedAt?: string;
  analytics?: EpisodeAnalytics;
  tags: string[];
}

export interface SeriesProject {
  id: string;
  name: string;
  description: string;
  episodes: SeriesEpisode[];
  brandAssets: BrandAsset[];
  analytics: {
    totalViews: number;
    totalWatchTimeMinutes: number;
    subscriberDelta: number;
    averageViewsPerEpisode: number;
  };
  defaultSettings: {
    resolution: { width: number; height: number };
    frameRate: number;
    exportFormat: string;
  };
  createdAt: string;
  updatedAt: string;
}

// ─── Podcast Mode (CC-08) ────────────────────────────────────────────────

export type FillerWordType = 'um' | 'uh' | 'like' | 'you_know' | 'so' | 'basically' | 'actually' | 'literally';

export interface SilenceRegion {
  startTime: number;
  endTime: number;
  duration: number;
}

export interface FillerWord {
  id: string;
  type: FillerWordType;
  startTime: number;
  endTime: number;
  confidence: number;
  removed: boolean;
}

export interface PodcastConfig {
  silenceGateMs: number;        // minimum silence duration to detect (ms)
  silenceThresholdDb: number;   // dB threshold for silence detection
  fillerWordRemoval: boolean;
  fillerWordTypes: FillerWordType[];
  chapterAutoGenerate: boolean;
  loudnessTarget: number;       // LUFS target
  crossfadeMs: number;          // crossfade for silence removal edits
  preserveBreathSounds: boolean;
}

export type PodcastExportFormat = 'mp3' | 'aac' | 'wav' | 'flac' | 'ogg';

export interface PodcastExportConfig {
  format: PodcastExportFormat;
  bitrate?: number;    // kbps for lossy formats
  sampleRate: number;
  channels: 1 | 2;
  includeChapters: boolean;
  includeArtwork: boolean;
  artworkUrl?: string;
  metadata: {
    title: string;
    artist: string;
    album?: string;
    genre?: string;
    year?: number;
    description?: string;
  };
}

// ─── Creator Workspace ───────────────────────────────────────────────────

export type CreatorWorkspacePreset = 'standard' | 'simplified' | 'podcast' | 'thumbnail' | 'series';

export interface CreatorWorkspaceConfig {
  preset: CreatorWorkspacePreset;
  showSourceBrowser: boolean;
  showRecordMonitor: boolean;
  showTimeline: boolean;
  showAIAssistant: boolean;
  showThumbnailDesigner: boolean;
  showStockBrowser: boolean;
  showBeatSync: boolean;
  showPodcastPanel: boolean;
  simplifiedMode: boolean;
}

export const WORKSPACE_PRESETS: Record<CreatorWorkspacePreset, CreatorWorkspaceConfig> = {
  standard: {
    preset: 'standard',
    showSourceBrowser: true,
    showRecordMonitor: true,
    showTimeline: true,
    showAIAssistant: true,
    showThumbnailDesigner: false,
    showStockBrowser: false,
    showBeatSync: false,
    showPodcastPanel: false,
    simplifiedMode: false,
  },
  simplified: {
    preset: 'simplified',
    showSourceBrowser: true,
    showRecordMonitor: true,
    showTimeline: true,
    showAIAssistant: true,
    showThumbnailDesigner: false,
    showStockBrowser: false,
    showBeatSync: false,
    showPodcastPanel: false,
    simplifiedMode: true,
  },
  podcast: {
    preset: 'podcast',
    showSourceBrowser: false,
    showRecordMonitor: false,
    showTimeline: true,
    showAIAssistant: true,
    showThumbnailDesigner: false,
    showStockBrowser: false,
    showBeatSync: false,
    showPodcastPanel: true,
    simplifiedMode: true,
  },
  thumbnail: {
    preset: 'thumbnail',
    showSourceBrowser: true,
    showRecordMonitor: true,
    showTimeline: false,
    showAIAssistant: true,
    showThumbnailDesigner: true,
    showStockBrowser: false,
    showBeatSync: false,
    showPodcastPanel: false,
    simplifiedMode: false,
  },
  series: {
    preset: 'series',
    showSourceBrowser: true,
    showRecordMonitor: true,
    showTimeline: true,
    showAIAssistant: true,
    showThumbnailDesigner: false,
    showStockBrowser: false,
    showBeatSync: false,
    showPodcastPanel: false,
    simplifiedMode: false,
  },
};
