// ═══════════════════════════════════════════════════════════════════════════
//  THE AVID — YouTube Chapter Exporter (CC-02)
//  Export chapter markers in YouTube format with AI suggestions
// ═══════════════════════════════════════════════════════════════════════════

import { generateId } from '../utils';
import {
  ChapterMarker,
  ChapterExportFormat,
  YouTubeMetadata,
} from './types';

// ─── Time Formatting ──────────────────────────────────────────────────────

function formatYouTubeTimestamp(seconds: number): string {
  const totalSeconds = Math.floor(seconds);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const secs = totalSeconds % 60;

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${minutes}:${secs.toString().padStart(2, '0')}`;
}

function formatSRTTimestamp(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.round((seconds % 1) * 1000);

  return [
    hours.toString().padStart(2, '0'),
    minutes.toString().padStart(2, '0'),
    secs.toString().padStart(2, '0'),
  ].join(':') + ',' + ms.toString().padStart(3, '0');
}

// ─── Chapter Validation ───────────────────────────────────────────────────

export interface ChapterValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

function validateChapters(chapters: ChapterMarker[]): ChapterValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (chapters.length === 0) {
    errors.push('At least one chapter marker is required.');
    return { valid: false, errors, warnings };
  }

  // YouTube requires first chapter at 0:00
  const sorted = [...chapters].sort((a, b) => a.time - b.time);
  if (sorted[0]!.time !== 0) {
    errors.push('First chapter must start at 0:00 for YouTube compatibility.');
  }

  // YouTube requires at least 3 chapters
  if (chapters.length < 3) {
    warnings.push('YouTube recommends at least 3 chapters for the feature to activate.');
  }

  // Each chapter must be at least 10 seconds
  for (let i = 0; i < sorted.length - 1; i++) {
    const duration = sorted[i + 1]!.time - sorted[i]!.time;
    if (duration < 10) {
      errors.push(
        `Chapter "${sorted[i]!.title}" is only ${duration.toFixed(1)}s long. YouTube requires at least 10 seconds per chapter.`,
      );
    }
  }

  // Check for empty titles
  for (const chapter of sorted) {
    if (!chapter.title.trim()) {
      errors.push('All chapters must have a non-empty title.');
    }
  }

  // Check for duplicate times
  const times = sorted.map((c) => c.time);
  const uniqueTimes = new Set(times);
  if (uniqueTimes.size !== times.length) {
    errors.push('Duplicate chapter timestamps detected.');
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

// ─── AI Chapter Suggestion ────────────────────────────────────────────────

interface TranscriptSegment {
  text: string;
  startTime: number;
  endTime: number;
  speaker?: string;
}

function suggestChaptersFromTranscript(
  segments: TranscriptSegment[],
  totalDuration: number,
): ChapterMarker[] {
  if (segments.length === 0) return [];

  const chapters: ChapterMarker[] = [];

  // Always start with a chapter at 0:00
  chapters.push({
    time: 0,
    title: 'Intro',
    isAutoGenerated: true,
    confidence: 0.85,
  });

  // Detect topic shifts based on gaps, speaker changes, and text patterns
  const topicShiftIndicators = [
    'so let\'s', 'moving on', 'next', 'now let\'s', 'another',
    'the first', 'the second', 'the third', 'finally',
    'in conclusion', 'to summarize', 'wrapping up',
    'question', 'topic', 'chapter', 'section', 'part',
  ];

  let lastChapterTime = 0;
  const minChapterGap = 30; // minimum 30 seconds between AI chapters

  for (let i = 1; i < segments.length; i++) {
    const prev = segments[i - 1];
    const curr = segments[i];
    const timeSinceLastChapter = curr!.startTime - lastChapterTime;

    if (timeSinceLastChapter < minChapterGap) continue;

    let score = 0;
    let suggestedTitle = '';

    // Check for significant silence gap (>2 seconds)
    const gap = curr!.startTime - prev!.endTime;
    if (gap > 2) score += 0.3;

    // Check for speaker change
    if (curr!.speaker && prev!.speaker && curr!.speaker !== prev!.speaker) {
      score += 0.2;
    }

    // Check for topic shift keywords
    const lowerText = curr!.text.toLowerCase();
    for (const indicator of topicShiftIndicators) {
      if (lowerText.includes(indicator)) {
        score += 0.4;
        // Extract a title from the text
        suggestedTitle = extractChapterTitle(curr!.text);
        break;
      }
    }

    // Check for time-based division (every ~5 minutes for long content)
    if (totalDuration > 600 && timeSinceLastChapter > 300) {
      score += 0.15;
    }

    if (score >= 0.35) {
      chapters.push({
        time: curr!.startTime,
        title: suggestedTitle || generateChapterTitle(i, curr!.text),
        isAutoGenerated: true,
        confidence: Math.min(0.95, score),
      });
      lastChapterTime = curr!.startTime;
    }
  }

  return chapters;
}

function extractChapterTitle(text: string): string {
  // Take first meaningful phrase (up to ~40 chars)
  const cleaned = text.replace(/^(so|okay|alright|now|and)\s+/i, '');
  const words = cleaned.split(/\s+/);
  let title = '';
  for (const word of words) {
    if ((title + ' ' + word).length > 40) break;
    title = title ? `${title} ${word}` : word;
  }
  // Capitalize first letter
  return title.charAt(0).toUpperCase() + title.slice(1);
}

function generateChapterTitle(index: number, text: string): string {
  // Fallback title generation
  const firstWords = text.split(/\s+/).slice(0, 5).join(' ');
  if (firstWords.length > 3) {
    return firstWords.charAt(0).toUpperCase() + firstWords.slice(1);
  }
  return `Section ${index}`;
}

// ─── Export Functions ─────────────────────────────────────────────────────

function exportToYouTubeFormat(chapters: ChapterMarker[]): string {
  const sorted = [...chapters].sort((a, b) => a.time - b.time);
  return sorted
    .map((chapter) => `${formatYouTubeTimestamp(chapter.time)} ${chapter.title}`)
    .join('\n');
}

function exportToSRTChapterFormat(chapters: ChapterMarker[]): string {
  const sorted = [...chapters].sort((a, b) => a.time - b.time);
  const lines: string[] = [];

  for (let i = 0; i < sorted.length; i++) {
    const chapter = sorted[i];
    const nextTime = i < sorted.length - 1 ? sorted[i + 1]!.time : chapter!.time + 30;

    lines.push(`${i + 1}`);
    lines.push(`${formatSRTTimestamp(chapter!.time)} --> ${formatSRTTimestamp(nextTime)}`);
    lines.push(chapter!.title);
    if (chapter!.description) {
      lines.push(chapter!.description);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function exportToJSON(chapters: ChapterMarker[]): string {
  const sorted = [...chapters].sort((a, b) => a.time - b.time);
  return JSON.stringify(
    sorted.map((c) => ({
      time: c.time,
      title: c.title,
      description: c.description,
      isAutoGenerated: c.isAutoGenerated,
    })),
    null,
    2,
  );
}

function exportToMarkdown(chapters: ChapterMarker[]): string {
  const sorted = [...chapters].sort((a, b) => a.time - b.time);
  const lines = ['# Chapters', ''];

  for (const chapter of sorted) {
    lines.push(`## ${formatYouTubeTimestamp(chapter.time)} - ${chapter.title}`);
    if (chapter.description) {
      lines.push('');
      lines.push(chapter.description);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ─── YouTube Metadata Builder ─────────────────────────────────────────────

function buildYouTubeDescription(
  metadata: YouTubeMetadata,
  additionalText?: string,
): string {
  const lines: string[] = [];

  if (metadata.description) {
    lines.push(metadata.description);
    lines.push('');
  }

  if (additionalText) {
    lines.push(additionalText);
    lines.push('');
  }

  // Add chapters
  if (metadata.chapters.length > 0) {
    lines.push('--- Chapters ---');
    const sorted = [...metadata.chapters].sort((a, b) => a.time - b.time);
    for (const chapter of sorted) {
      lines.push(`${formatYouTubeTimestamp(chapter.time)} ${chapter.title}`);
    }
    lines.push('');
  }

  // Add tags as hashtags
  if (metadata.tags.length > 0) {
    lines.push(metadata.tags.map((t) => `#${t.replace(/\s+/g, '')}`).join(' '));
  }

  return lines.join('\n');
}

// ─── Main Exporter Class ─────────────────────────────────────────────────

export class YouTubeChapterExporter {
  private chapters: ChapterMarker[] = [];

  constructor(chapters?: ChapterMarker[]) {
    if (chapters) {
      this.chapters = [...chapters];
    }
  }

  /**
   * Add a chapter marker
   */
  addChapter(chapter: ChapterMarker): void {
    this.chapters.push(chapter);
    this.chapters.sort((a, b) => a.time - b.time);
  }

  /**
   * Remove a chapter by time
   */
  removeChapterAtTime(time: number): void {
    this.chapters = this.chapters.filter((c) => c.time !== time);
  }

  /**
   * Replace all chapters
   */
  setChapters(chapters: ChapterMarker[]): void {
    this.chapters = [...chapters].sort((a, b) => a.time - b.time);
  }

  /**
   * Get current chapters
   */
  getChapters(): ChapterMarker[] {
    return [...this.chapters];
  }

  /**
   * Validate chapters for YouTube compatibility
   */
  validate(): ChapterValidationResult {
    return validateChapters(this.chapters);
  }

  /**
   * Auto-generate chapters from transcript
   */
  suggestFromTranscript(
    segments: TranscriptSegment[],
    totalDuration: number,
  ): ChapterMarker[] {
    const suggested = suggestChaptersFromTranscript(segments, totalDuration);
    return suggested;
  }

  /**
   * Merge AI suggestions with manually created chapters
   */
  mergeWithSuggestions(suggestions: ChapterMarker[]): void {
    // Keep manual chapters, add AI suggestions that don't conflict
    const manualTimes = new Set(
      this.chapters.filter((c) => !c.isAutoGenerated).map((c) => c.time),
    );

    for (const suggestion of suggestions) {
      // Skip if too close to an existing manual chapter (within 5 seconds)
      const tooClose = this.chapters.some(
        (c) => !c.isAutoGenerated && Math.abs(c.time - suggestion.time) < 5,
      );
      if (!tooClose && !manualTimes.has(suggestion.time)) {
        this.chapters.push(suggestion);
      }
    }

    this.chapters.sort((a, b) => a.time - b.time);
  }

  /**
   * Export chapters in specified format
   */
  export(format: ChapterExportFormat): string {
    switch (format) {
      case 'youtube':
        return exportToYouTubeFormat(this.chapters);
      case 'srt_chapters':
        return exportToSRTChapterFormat(this.chapters);
      case 'json':
        return exportToJSON(this.chapters);
      case 'markdown':
        return exportToMarkdown(this.chapters);
      default:
        return exportToYouTubeFormat(this.chapters);
    }
  }

  /**
   * Build full YouTube metadata including chapters in description
   */
  buildYouTubeMetadata(
    options: Omit<YouTubeMetadata, 'chapters'>,
  ): YouTubeMetadata & { formattedDescription: string } {
    const metadata: YouTubeMetadata = {
      ...options,
      chapters: this.chapters,
    };

    return {
      ...metadata,
      formattedDescription: buildYouTubeDescription(metadata),
    };
  }

  /**
   * Ensure first chapter starts at 0:00
   */
  ensureIntroChapter(title = 'Intro'): void {
    const hasZero = this.chapters.some((c) => c.time === 0);
    if (!hasZero) {
      this.chapters.unshift({
        time: 0,
        title,
        isAutoGenerated: false,
      });
    }
  }
}

// ─── Factory ──────────────────────────────────────────────────────────────

export function createYouTubeChapterExporter(chapters?: ChapterMarker[]): YouTubeChapterExporter {
  return new YouTubeChapterExporter(chapters);
}
