// =============================================================================
//  THE AVID — Codec Capability Matrix
//  Complete registry of supported formats for both native (desktop) and
//  browser (web) implementations. Drives the UI's format support indicators
//  and the codec selection logic in export/transcode workflows.
// =============================================================================

import type { CodecCapability } from './types';

// ─── Full Native Capabilities (Desktop via FFmpeg + LibRaw + OpenEXR) ───────

export const FULL_CODEC_CAPABILITIES: CodecCapability[] = [
  // ── Video Codecs ──────────────────────────────────────────────────────

  {
    codecId: 'h264',
    name: 'H.264 / AVC',
    category: 'video',
    extensions: ['mp4', 'm4v', 'mkv', 'avi', 'mov', 'ts'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: true,
    hwAccelEncode: true,
    bitDepths: [8, 10],
    alpha: false,
    maxResolution: 8192,
  },
  {
    codecId: 'h265',
    name: 'H.265 / HEVC',
    category: 'video',
    extensions: ['mp4', 'mkv', 'mov', 'ts'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: true,
    hwAccelEncode: true,
    bitDepths: [8, 10, 12],
    alpha: false,
    maxResolution: 8192,
  },
  {
    codecId: 'av1',
    name: 'AV1',
    category: 'video',
    extensions: ['mp4', 'mkv', 'webm'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: true,
    hwAccelEncode: true,
    bitDepths: [8, 10, 12],
    alpha: false,
    maxResolution: 8192,
  },
  {
    codecId: 'vp9',
    name: 'VP9',
    category: 'video',
    extensions: ['webm', 'mkv'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: true,
    hwAccelEncode: false,
    bitDepths: [8, 10, 12],
    alpha: true,
    maxResolution: 8192,
  },
  {
    codecId: 'vp8',
    name: 'VP8',
    category: 'video',
    extensions: ['webm', 'mkv'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: true,
    maxResolution: 4096,
  },
  {
    codecId: 'prores422',
    name: 'Apple ProRes 422',
    category: 'video',
    extensions: ['mov', 'mxf'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [10],
    alpha: false,
    maxResolution: 8192,
  },
  {
    codecId: 'prores4444',
    name: 'Apple ProRes 4444',
    category: 'video',
    extensions: ['mov', 'mxf'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [10, 12],
    alpha: true,
    maxResolution: 8192,
  },
  {
    codecId: 'proresxq',
    name: 'Apple ProRes 4444 XQ',
    category: 'video',
    extensions: ['mov'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [12],
    alpha: true,
    maxResolution: 8192,
  },
  {
    codecId: 'dnxhd',
    name: 'Avid DNxHD',
    category: 'video',
    extensions: ['mxf', 'mov'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: false,
    maxResolution: 1920,
  },
  {
    codecId: 'dnxhr',
    name: 'Avid DNxHR',
    category: 'video',
    extensions: ['mxf', 'mov'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8, 10, 12],
    alpha: false,
    maxResolution: 8192,
  },
  {
    codecId: 'cineform',
    name: 'GoPro CineForm',
    category: 'video',
    extensions: ['mov', 'avi'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [10, 12],
    alpha: true,
    maxResolution: 8192,
  },
  {
    codecId: 'hap',
    name: 'HAP',
    category: 'video',
    extensions: ['mov', 'avi'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: true,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: true,
    maxResolution: 4096,
  },
  {
    codecId: 'mpeg2',
    name: 'MPEG-2',
    category: 'video',
    extensions: ['mpg', 'mpeg', 'ts', 'mxf', 'vob'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: true,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: false,
    maxResolution: 1920,
  },
  {
    codecId: 'mpeg4',
    name: 'MPEG-4 Part 2',
    category: 'video',
    extensions: ['avi', 'mp4'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: false,
    maxResolution: 1920,
  },
  {
    codecId: 'mjpeg',
    name: 'Motion JPEG',
    category: 'video',
    extensions: ['avi', 'mov'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: false,
    maxResolution: 4096,
  },
  {
    codecId: 'theora',
    name: 'Theora',
    category: 'video',
    extensions: ['ogv', 'ogg'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: false,
    maxResolution: 4096,
  },
  {
    codecId: 'rawvideo',
    name: 'Uncompressed Video',
    category: 'video',
    extensions: ['avi', 'mov'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8, 10, 12, 16],
    alpha: true,
    maxResolution: 0,
  },

  // ── Camera RAW Formats ────────────────────────────────────────────────

  {
    codecId: 'arriraw',
    name: 'ARRI ARRIRAW',
    category: 'raw',
    extensions: ['ari'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: true,
    hwAccelEncode: false,
    bitDepths: [12, 16],
    alpha: false,
    maxResolution: 6560,
  },
  {
    codecId: 'red_r3d',
    name: 'RED R3D',
    category: 'raw',
    extensions: ['r3d'],
    decodeTier: 'adapter',
    encodeTier: 'unsupported',
    hwAccelDecode: true,
    hwAccelEncode: false,
    bitDepths: [16],
    alpha: false,
    maxResolution: 8192,
  },
  {
    codecId: 'braw',
    name: 'Blackmagic RAW',
    category: 'raw',
    extensions: ['braw'],
    decodeTier: 'adapter',
    encodeTier: 'unsupported',
    hwAccelDecode: true,
    hwAccelEncode: false,
    bitDepths: [12, 16],
    alpha: false,
    maxResolution: 12288,
  },
  {
    codecId: 'dng',
    name: 'CinemaDNG / DNG',
    category: 'raw',
    extensions: ['dng'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: true,
    hwAccelEncode: false,
    bitDepths: [12, 14, 16],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'cr3',
    name: 'Canon CR3 / CR2',
    category: 'raw',
    extensions: ['cr3', 'cr2'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [14],
    alpha: false,
    maxResolution: 8192,
  },
  {
    codecId: 'arw',
    name: 'Sony ARW',
    category: 'raw',
    extensions: ['arw', 'srf', 'sr2'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [14],
    alpha: false,
    maxResolution: 9504,
  },
  {
    codecId: 'nef',
    name: 'Nikon NEF / NRW',
    category: 'raw',
    extensions: ['nef', 'nrw'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [12, 14],
    alpha: false,
    maxResolution: 8256,
  },
  {
    codecId: 'raf',
    name: 'Fujifilm RAF',
    category: 'raw',
    extensions: ['raf'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [14],
    alpha: false,
    maxResolution: 9504,
  },
  {
    codecId: 'rw2',
    name: 'Panasonic RW2',
    category: 'raw',
    extensions: ['rw2'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [12, 14],
    alpha: false,
    maxResolution: 6000,
  },
  {
    codecId: 'iiq',
    name: 'Phase One IIQ',
    category: 'raw',
    extensions: ['iiq'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16],
    alpha: false,
    maxResolution: 15100,
  },

  // ── Image Sequence Formats ────────────────────────────────────────────

  {
    codecId: 'exr',
    name: 'OpenEXR',
    category: 'image',
    extensions: ['exr'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16, 32],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'dpx',
    name: 'DPX (Digital Picture Exchange)',
    category: 'image',
    extensions: ['dpx'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [10, 12, 16],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'tiff',
    name: 'TIFF',
    category: 'image',
    extensions: ['tiff', 'tif'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8, 16, 32],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'png',
    name: 'PNG',
    category: 'image',
    extensions: ['png'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8, 16],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'jpeg',
    name: 'JPEG',
    category: 'image',
    extensions: ['jpg', 'jpeg'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'webp',
    name: 'WebP',
    category: 'image',
    extensions: ['webp'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: true,
    maxResolution: 16383,
  },
  {
    codecId: 'bmp',
    name: 'BMP',
    category: 'image',
    extensions: ['bmp'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'tga',
    name: 'Targa TGA',
    category: 'image',
    extensions: ['tga'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'sgi',
    name: 'SGI RGB',
    category: 'image',
    extensions: ['sgi', 'rgb'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8, 16],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'cineon',
    name: 'Cineon',
    category: 'image',
    extensions: ['cin'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [10],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'hdr',
    name: 'Radiance HDR',
    category: 'image',
    extensions: ['hdr', 'rgbe'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [32],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'pfm',
    name: 'Portable Float Map',
    category: 'image',
    extensions: ['pfm'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [32],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'svg',
    name: 'SVG (Scalable Vector Graphics)',
    category: 'image',
    extensions: ['svg'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'avif',
    name: 'AVIF',
    category: 'image',
    extensions: ['avif'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8, 10, 12],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'gif',
    name: 'GIF',
    category: 'image',
    extensions: ['gif'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [8],
    alpha: true,
    maxResolution: 0,
  },

  // ── Audio Codecs ──────────────────────────────────────────────────────

  {
    codecId: 'aac',
    name: 'AAC',
    category: 'audio',
    extensions: ['aac', 'm4a', 'mp4'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16, 24],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'mp3',
    name: 'MP3',
    category: 'audio',
    extensions: ['mp3'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'pcm',
    name: 'PCM / WAV (Uncompressed)',
    category: 'audio',
    extensions: ['wav'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16, 24, 32],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'flac',
    name: 'FLAC (Lossless)',
    category: 'audio',
    extensions: ['flac'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16, 24],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'alac',
    name: 'Apple Lossless (ALAC)',
    category: 'audio',
    extensions: ['m4a', 'caf'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16, 24, 32],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'opus',
    name: 'Opus',
    category: 'audio',
    extensions: ['opus', 'ogg', 'webm'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'vorbis',
    name: 'Vorbis',
    category: 'audio',
    extensions: ['ogg'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'aiff',
    name: 'AIFF',
    category: 'audio',
    extensions: ['aiff', 'aif'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16, 24, 32],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'ac3',
    name: 'Dolby Digital (AC-3)',
    category: 'audio',
    extensions: ['ac3'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'eac3',
    name: 'Dolby Digital Plus (E-AC-3)',
    category: 'audio',
    extensions: ['eac3'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16, 24],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'dts',
    name: 'DTS',
    category: 'audio',
    extensions: ['dts'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16, 24],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'wma',
    name: 'Windows Media Audio',
    category: 'audio',
    extensions: ['wma'],
    decodeTier: 'native',
    encodeTier: 'unsupported',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [16],
    alpha: false,
    maxResolution: 0,
  },

  // ── Container Formats ─────────────────────────────────────────────────

  {
    codecId: 'mp4',
    name: 'MPEG-4 Part 14 (MP4)',
    category: 'container',
    extensions: ['mp4', 'm4v'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'mov',
    name: 'QuickTime (MOV)',
    category: 'container',
    extensions: ['mov'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'mxf',
    name: 'Material Exchange Format (MXF)',
    category: 'container',
    extensions: ['mxf'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'mkv',
    name: 'Matroska (MKV)',
    category: 'container',
    extensions: ['mkv'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'webm',
    name: 'WebM',
    category: 'container',
    extensions: ['webm'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [],
    alpha: true,
    maxResolution: 0,
  },
  {
    codecId: 'avi',
    name: 'AVI',
    category: 'container',
    extensions: ['avi'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'mpeg-ts',
    name: 'MPEG Transport Stream',
    category: 'container',
    extensions: ['ts', 'mts', 'm2ts'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'flv',
    name: 'Flash Video (FLV)',
    category: 'container',
    extensions: ['flv'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [],
    alpha: false,
    maxResolution: 0,
  },
  {
    codecId: 'ogg',
    name: 'OGG',
    category: 'container',
    extensions: ['ogg', 'ogv'],
    decodeTier: 'native',
    encodeTier: 'native',
    hwAccelDecode: false,
    hwAccelEncode: false,
    bitDepths: [],
    alpha: false,
    maxResolution: 0,
  },
];

// ─── Browser-Only Capabilities (WebCodecs + HTMLVideoElement) ────────────────

export const BROWSER_CODEC_CAPABILITIES: CodecCapability[] = [
  // Video (browser-native)
  {
    codecId: 'h264', name: 'H.264 / AVC', category: 'video',
    extensions: ['mp4', 'm4v', 'mkv', 'mov'],
    decodeTier: 'native', encodeTier: 'native',
    hwAccelDecode: true, hwAccelEncode: true,
    bitDepths: [8], alpha: false, maxResolution: 4096,
  },
  {
    codecId: 'h265', name: 'H.265 / HEVC', category: 'video',
    extensions: ['mp4', 'mkv', 'mov'],
    decodeTier: 'normalized', encodeTier: 'unsupported',
    hwAccelDecode: true, hwAccelEncode: false,
    bitDepths: [8, 10], alpha: false, maxResolution: 4096,
  },
  {
    codecId: 'av1', name: 'AV1', category: 'video',
    extensions: ['mp4', 'mkv', 'webm'],
    decodeTier: 'native', encodeTier: 'unsupported',
    hwAccelDecode: true, hwAccelEncode: false,
    bitDepths: [8, 10], alpha: false, maxResolution: 4096,
  },
  {
    codecId: 'vp9', name: 'VP9', category: 'video',
    extensions: ['webm', 'mkv'],
    decodeTier: 'native', encodeTier: 'native',
    hwAccelDecode: true, hwAccelEncode: false,
    bitDepths: [8], alpha: true, maxResolution: 4096,
  },
  {
    codecId: 'vp8', name: 'VP8', category: 'video',
    extensions: ['webm'],
    decodeTier: 'native', encodeTier: 'native',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [8], alpha: true, maxResolution: 4096,
  },
  // Audio (browser-native)
  {
    codecId: 'aac', name: 'AAC', category: 'audio',
    extensions: ['aac', 'm4a', 'mp4'],
    decodeTier: 'native', encodeTier: 'native',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [16], alpha: false, maxResolution: 0,
  },
  {
    codecId: 'mp3', name: 'MP3', category: 'audio',
    extensions: ['mp3'],
    decodeTier: 'native', encodeTier: 'unsupported',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [16], alpha: false, maxResolution: 0,
  },
  {
    codecId: 'opus', name: 'Opus', category: 'audio',
    extensions: ['opus', 'ogg', 'webm'],
    decodeTier: 'native', encodeTier: 'native',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [16], alpha: false, maxResolution: 0,
  },
  {
    codecId: 'pcm', name: 'PCM / WAV', category: 'audio',
    extensions: ['wav'],
    decodeTier: 'native', encodeTier: 'unsupported',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [16], alpha: false, maxResolution: 0,
  },
  {
    codecId: 'flac', name: 'FLAC', category: 'audio',
    extensions: ['flac'],
    decodeTier: 'normalized', encodeTier: 'unsupported',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [16], alpha: false, maxResolution: 0,
  },
  // Images (browser-native)
  {
    codecId: 'png', name: 'PNG', category: 'image',
    extensions: ['png'],
    decodeTier: 'native', encodeTier: 'native',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [8], alpha: true, maxResolution: 0,
  },
  {
    codecId: 'jpeg', name: 'JPEG', category: 'image',
    extensions: ['jpg', 'jpeg'],
    decodeTier: 'native', encodeTier: 'native',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [8], alpha: false, maxResolution: 0,
  },
  {
    codecId: 'webp', name: 'WebP', category: 'image',
    extensions: ['webp'],
    decodeTier: 'native', encodeTier: 'native',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [8], alpha: true, maxResolution: 0,
  },
  {
    codecId: 'svg', name: 'SVG', category: 'image',
    extensions: ['svg'],
    decodeTier: 'native', encodeTier: 'unsupported',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [8], alpha: true, maxResolution: 0,
  },
  {
    codecId: 'gif', name: 'GIF', category: 'image',
    extensions: ['gif'],
    decodeTier: 'native', encodeTier: 'unsupported',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [8], alpha: true, maxResolution: 0,
  },
  {
    codecId: 'avif', name: 'AVIF', category: 'image',
    extensions: ['avif'],
    decodeTier: 'native', encodeTier: 'unsupported',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [8, 10], alpha: true, maxResolution: 0,
  },
  // Containers (browser-native)
  {
    codecId: 'mp4', name: 'MP4', category: 'container',
    extensions: ['mp4', 'm4v'],
    decodeTier: 'native', encodeTier: 'unsupported',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [], alpha: false, maxResolution: 0,
  },
  {
    codecId: 'webm', name: 'WebM', category: 'container',
    extensions: ['webm'],
    decodeTier: 'native', encodeTier: 'native',
    hwAccelDecode: false, hwAccelEncode: false,
    bitDepths: [], alpha: true, maxResolution: 0,
  },
];
