import type React from 'react';

/** Shared inline styles for all settings sections. */
export const settingStyles: Record<string, React.CSSProperties> = {
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  sectionTitle: {
    margin: 0,
    fontSize: 14,
    fontWeight: 700,
    color: 'var(--text-primary, #e8e8ed)',
  },
  resetBtn: {
    padding: '4px 10px',
    borderRadius: 'var(--radius-sm, 4px)',
    border: '1px solid var(--border-default, #2a2a35)',
    background: 'transparent',
    color: 'var(--text-muted, #6a6a7a)',
    fontSize: 11,
    fontWeight: 500,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  field: {
    marginBottom: 18,
  },
  label: {
    display: 'block',
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--text-secondary, #a0a0b0)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
    marginBottom: 6,
  },
  input: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: 'var(--radius-md, 6px)',
    border: '1px solid var(--border-default, #2a2a35)',
    background: 'var(--bg-void, #0a0a0f)',
    color: 'var(--text-primary, #e8e8ed)',
    fontSize: 13,
    fontFamily: 'inherit',
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  select: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: 'var(--radius-md, 6px)',
    border: '1px solid var(--border-default, #2a2a35)',
    background: 'var(--bg-void, #0a0a0f)',
    color: 'var(--text-primary, #e8e8ed)',
    fontSize: 13,
    fontFamily: 'inherit',
    outline: 'none',
    boxSizing: 'border-box' as const,
    cursor: 'pointer',
  },
  radioGroup: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 12,
  },
  radioLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 12,
    color: 'var(--text-primary, #e8e8ed)',
    cursor: 'pointer',
  },
  radio: {
    accentColor: 'var(--brand, #6d4cfa)',
  },
  toggleLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 12,
    color: 'var(--text-primary, #e8e8ed)',
    cursor: 'pointer',
  },
  checkbox: {
    accentColor: 'var(--brand, #6d4cfa)',
    width: 14,
    height: 14,
  },
  range: {
    width: '100%',
    accentColor: 'var(--brand, #6d4cfa)',
    cursor: 'pointer',
  },
  rangeLabels: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 10,
    color: 'var(--text-muted, #6a6a7a)',
    marginTop: 4,
  },
};
