/**
 * @module workflows/generative-motion-cleanup
 * @description Generative/VFX vertical — motion stabilisation and clean plate generation.
 *
 * This workflow models a VFX artist's composite preparation task: stabilising
 * camera shake on the hero talent plate, verifying audio sync after
 * stabilisation, performing a green-screen key extraction, and applying a
 * finishing colour grade to blend the composite layers.
 *
 * Failure strategy:
 * - `detect_scene_changes` is the analysis foundation; failure aborts.
 * - `analyze_audio` for sync verification is important; retries once.
 * - The stabilise and green-screen steps are core VFX operations modelled as
 *   advisory tool calls; failures retry once before skipping.
 * - `apply_color_grade` is the finishing pass; failure skips gracefully since
 *   the composite can be graded manually.
 */

import type { WorkflowDefinition } from './types';

/**
 * Generative Motion Cleanup workflow.
 *
 * Prompt: "Add subtle camera shake removal and generate a clean background plate
 *          behind the green screen"
 *
 * Pipeline:
 * 1. Detect scene changes to identify stable vs. shaky segments.
 * 2. Analyse audio to flag any sync drift that stabilisation might introduce.
 * 3. Stabilise the hero talent plate (modelled as detect_scene_changes with
 *    stabilisation metadata — real implementation calls a VFX adapter).
 * 4. Extract the green-screen key to isolate talent from the chroma plate
 *    (modelled as find_similar_clips with keying parameters).
 * 5. Apply a cinematic colour grade to blend the composite layers.
 */
export const GENERATIVE_MOTION_CLEANUP: WorkflowDefinition = {
  id: 'generative-motion-cleanup',
  name: 'Generative VFX — Stabilise + Clean Plate',
  description:
    'Remove camera shake from the hero talent plate, extract a green-screen key, ' +
    'and apply a cinematic grade to blend the composite layers.',
  vertical: 'generative',
  demoPrompt:
    'Add subtle camera shake removal and generate a clean background plate behind the green screen',
  seedDataId: 'generative-vfx',
  estimatedDurationMs: 25_000,
  estimatedTokenCost: 350,
  steps: [
    {
      toolName: 'detect_scene_changes',
      description: 'Analyse the hero plate for scene boundaries and motion instability',
      expectedResult:
        'Identifies 3 segments: a stable locked-off portion (0-8s), a moderate-shake ' +
        'handheld section (8-22s), and a return to stability (22-30s). Shake magnitude ' +
        'peaks at 4.2 pixels RMS in the middle segment.',
      failureHandler: 'abort',
    },
    {
      toolName: 'analyze_audio',
      description: 'Verify audio sync baseline before stabilisation transforms',
      expectedResult:
        'Audio-video sync confirmed within 1 frame tolerance. No drift detected. ' +
        'Waveform reference snapshot stored for post-stabilisation comparison.',
      failureHandler: 'retry',
    },
    {
      toolName: 'detect_scene_changes',
      description: 'Apply motion stabilisation to the shaky hero plate segment',
      expectedResult:
        'Camera shake reduced from 4.2px RMS to 0.3px RMS in the middle segment. ' +
        'Edge crop of 2.8% applied with smart fill to maintain framing. ' +
        'Audio sync re-verified within tolerance.',
      failureHandler: 'retry',
    },
    {
      toolName: 'find_similar_clips',
      description: 'Extract green-screen key and generate a clean background plate',
      expectedResult:
        'Chroma key extracted with 98.7% edge accuracy. Clean plate generated by ' +
        'compositing the cityscape sunset background behind the keyed talent. ' +
        'Spill suppression applied to green fringing on hair edges.',
      failureHandler: 'retry',
    },
    {
      toolName: 'apply_color_grade',
      description: 'Apply a cinematic colour grade to unify the composite layers',
      expectedResult:
        'Warm cinematic grade applied: lifted shadows (R+8, G+4), desaturated highlights, ' +
        'and a subtle teal-orange split tone. All layers (talent, background, particles) ' +
        'graded consistently for a cohesive final composite.',
      failureHandler: 'skip',
    },
  ],
};
